[tool.poetry]
name = "indicodata-celery"
version = "5.4.0"
description = "Indico shared utilities"
authors = ["Indico Data <engineering@indicodata.ai>"]
packages = [ {include = "celery"}]

[tool.poetry.dependencies]
python = "^3.7"
pytz = "^2021.3"
billiard = "^3.6.4"
kombu = "^5.2.3"
vine = "^5.0.0"
click = "^8.0.3"
click-didyoumean = "^0.0.3"
click-repl = "^0.2.0"
click-plugins = "^1.1.1"
setuptools = "*"

[tool.poetry.scripts]
celery = "celery.__main__:main"

[tool.pytest.ini_options]
addopts = "--strict-markers"
testpaths = "t/unit/"
python_classes = "test_*"
xdfail_strict=true
markers = ["sleepdeprived_patched_module", "masked_modules", "patched_environ", "patched_module"]

[tool.semantic_release]
version_variable = "celery/__init__.py:__version__"
version_toml = ["pyproject.toml:tool.poetry.version"]
branch = "main"
upload_to_respository=true
repository_url="https://push.fury.io/indico"
build_command="poetry build"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
xfail_strict=true
markers = ["sleepdeprived_patched_module", "masked_modules", "patched_environ", "patched_module", "flaky", "timeout", "amqp"]

[tool.mypy]
warn_unused_configs = true
strict = false
follow_imports = "skip"
show_error_codes = true
disallow_untyped_defs = true
ignore_missing_imports = true
files = [
    "celery/__main__.py",
    "celery/states.py",
    "celery/signals.py",
    "celery/fixups",
    "celery/concurrency/thread.py",
    "celery/security/certificate.py",
    "celery/utils/text.py",
    "celery/schedules.py",
    "celery/apps/beat.py",
]

[tool.codespell]
ignore-words-list = "assertin"
skip = "./.*,docs/AUTHORS.txt,docs/history/*,docs/spelling_wordlist.txt,Changelog.rst,CONTRIBUTORS.txt,*.key"

[tool.coverage.run]
branch = true
cover_pylib = false
include = ["*celery/*"]
omit = ["celery.tests.*"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "except ImportError:"
]
omit = [
    "*/python?.?/*",
    "*/site-packages/*",
    "*/pypy/*",
    "*/celery/bin/graph.py",
    "*celery/bin/logtool.py",
    "*celery/task/base.py",
    "*celery/contrib/sphinx.py",
    "*celery/concurrency/asynpool.py",
    "*celery/utils/debug.py",
    "*celery/contrib/testing/*",
    "*celery/contrib/pytest.py"
]
